# Generated by Django 4.1.2 on 2023-06-12 13:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeapi_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('effect_entry', models.CharField(max_length=500)),
                ('effect_entry_short', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeapi_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('base_experience', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('image_big', models.ImageField(null=True, upload_to='pokemon_images_big/')),
                ('image_small_front', models.ImageField(null=True, upload_to='pokemon_images_small_front/')),
                ('image_small_back', models.ImageField(null=True, upload_to='pokemon_images_small_back/')),
                ('abilities', models.ManyToManyField(to='pokemon.ability')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Моя коллекция', max_length=100)),
                ('pokemons', models.ManyToManyField(to='pokemon.pokemon')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
