# Generated by Django 4.1.2 on 2023-06-13 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='base_experience',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_big',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_images_big/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_small_back',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_images_small_back/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_small_front',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_images_small_front/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
