# Generated by Django 4.1.2 on 2023-06-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_base_experience_alter_pokemon_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePokemon',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='pokemon.typepokemon'),
        ),
    ]
