# Generated by Django 4.1.2 on 2023-07-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_typepokemon_pokemon_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='typepokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='type_image/'),
        ),
    ]
