# Generated by Django 4.1.2 on 2023-07-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_typepokemon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesPokemon',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.speciespokemon'),
        ),
    ]
