# Generated by Django 4.1.2 on 2023-07-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_speciespokemon_pokemon_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemons', to='pokemon.speciespokemon'),
        ),
    ]
